name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.1'

    - name: Build
      run: |
        echo "//PramithaMJ:***" > ~/.npmrc
        cd pkg/slack
        go mod tidy
        go mod vendor
        go build -o ./bin/slack-sdk-go .
      env:
        GOROOT: /opt/hostedtoolcache/go/1.22.1/x64
        GITHUB_TOKEN: ${{ secrets.GITHUB_PKG_TOKEN }}

    - name: Publish to GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_PKG_TOKEN }}" > ~/.npmrc
        GOPROXY=https://npm.pkg.github.com go mod tidy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PKG_TOKEN }}
